apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-neo4j-connect
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka-neo4j-connect
        image: "veedata/kafka-neo4j-connect"
        ports:
        - containerPort: 8083